### ISSUE TITLE
Migrate to new Blockscout UI 

### ISSUE THREAD

**Issue by PolinaKiporenko** [skalenetwork/skale-explorer#28]
Migrate to new Blockscout UI  https://base.blockscout.com/ 
```[tasklist]
### Tasks
- [x] Hide gas tracker
- [x] Remove banners and ads
- [x] Add read/write contract methods
- [x] Read genesis block from config
- [x] Remove `testnet` label
- [x] Add networks
- [x] Integrate new blockscout version in skale-explorer
- [x] Fetch chain app name
- [x] Update networks config
- [x] Access to blockscout via https and domain
- [x] Add testnet label for chains from testnet
- [x] Migrate data from previous version
- [x] Migrate hubs
- [x] Migrate mainnet appchains
- [x] Use fixed versions of blockscout containers
- [x] Migrate testnet blockscouts
```
